# The configuration file for the GenAI-MIDI-module

# Metadata about this configuration
title = "OP1 in Volca FM out"
owner = "Charles and Yichen"
description = "Uses OP1 over it's USB connection and Volca FM over RPi serial"

# Basic config
log_input = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "callresponse" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 0.1 # number of seconds before switching in call-response mode
input_thru = false # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 9
file = "models/musicMDRNN-dim9-layers2-units64-mixtures5-scale10.tflite"
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

# MIDI Mapping
[midi]
in_device = "OP-1"
out_device = "MIDI Through"
input = [ # XTOUCH-MINI knobs
  ["note_on", 1], # note
  ["control_change", 11, 2], # XTOUCH-MINI knob controller 2
  ["note_on", 1], # note
  ["control_change", 11, 3], # XTOUCH-MINI knob controller 3
  ["note_on", 1], # note
  ["control_change", 11, 6], # XTOUCH-MINI knob controller 6
  ["note_on", 1], # note
  ["control_change", 11, 7], # XTOUCH-MINI knob controller 7
]
output = [ # Volca FM
  ["note_on", 1], # note
  ["control_change", 1, 42], # Modulator Attack
  ["control_change", 1, 43], # Modulator Decay
  ["control_change", 1, 44], # Carrier Attack
  ["control_change", 1, 45], # Carrier Decay
  ["control_change", 1, 46], # LFO rate
  ["control_change", 1, 47], # LFO depth
  ["control_change", 1, 48], # Algorithm
]

[websocket]
server_ip = "0.0.0.0" # The address of this server
server_port = 5001 # The port this server should listen on.