# The configuration file for IMPSY: Interactive Musical Prediction System

# Metadata about this configuration
title = "Roland S-1 to S-1"
owner = "Charles Martin"
description = "A self-contained config for the Roland S-1"

# Basic config
log_input = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "callresponse" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 0.1 # number of seconds before switching in call-response mode
input_thru = false # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 9
file = "models/musicMDRNN-dim9-layers2-units64-mixtures5-scale10.tflite"
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

# MIDI Mapping
# MIDI Mapping
[midi]
in_device = "S-1"
out_device = "S-1"
input = [
  ["control_change", 3, 13], # osc lfo
  ["control_change", 3, 19], # osc square level
  ["control_change", 3, 20], # osc tri level
  ["control_change", 3, 21], # osc sub level
  ["control_change", 3, 23], # osc noise level
  ["control_change", 3, 24], # filter env knob
  ["control_change", 3, 25], # filter lfo knob
  ["control_change", 3, 71], # filter reso knob
]
output = [
  ["note_on", 3], # notes input
  ["control_change", 3, 19], # osc square level
  ["control_change", 3, 20], # osc tri level
  ["control_change", 3, 21], # osc sub level
  ["control_change", 3, 23], # osc noise level
  ["control_change", 3, 24], # filter env knob
  ["control_change", 3, 25], # filter lfo knob
  ["control_change", 3, 71], # filter reso knob
]

  # ["control_change", 3, 3], # lfo rate
  # ["control_change", 3, 13], # osc lfo
  # ["control_change", 3, 3], # lfo rate
  # ["note_on", 3], # notes input
