# The configuration file for IMPSY: Interactive Musical Prediction System

# Metadata about this configuration
title = "Microbit Serial Demo"
owner = "Charles Martin"
description = "Communicates with a microbit interface over serial."

# Basic config
log_input = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "callresponse" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 0.1 # number of seconds before switching in call-response mode
input_thru = false # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 4
file = "models/musicMDRNN-dim4-layers2-units64-mixtures5-scale10.tflite"
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

# Serial mapping
[serial]
port = "/dev/tty.usbmodem1102" # likely serial port on macOS
# port = "/dev/ttyACM0" # likely serial port on Raspberry Pi (also the default GPIO serial port name if enabled).
baudrate = 115200 # a typical default choice of baudrate
