# The configuration file for IMPSY: Interactive Musical Prediction System

# Metadata about this configuration
title = "Testing a user-only configuration"
owner = "Charles Martin"
description = ""

# Basic config
log_input = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "useronly" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 0.1 # number of seconds before switching in call-response mode
input_thru = false # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 17
# file = "" # No model file! Uses untrained model.
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

[osc]
server_ip = "0.0.0.0" # Address of IMPSY
server_port = 6000 # Port IMPSY listens on
client_ip = "0.0.0.0" # Address of the output device
client_port = 6001 # Port of the output device
