# The configuration file for IMPSY: Interactive Musical Prediction System

# Metadata about this configuration
title = "X-TOUCH in Volca Keys out"
owner = "Charles Martin"
description = "Uses x-touch over it's own USB connector and Volca Keys over the Studio 1824c"

# Basic config
log_input = true
log_predictions = false
verbose = true

# Interaction Configuration
[interaction]
mode = "callresponse" # Can be: "callresponse", "polyphony", "battle", "useronly"
threshold = 0.1 # number of seconds before switching in call-response mode
input_thru = true # sends inputs directly to outputs (e.g., if input interface is different than output synth)

# Model configuration
[model]
dimension = 9
file = "models/musicMDRNN-dim9-layers2-units64-mixtures5-scale10.keras"
size = "s" # Can be one of: xs, s, m, l, xl
sigmatemp = 0.01
pitemp = 1
timescale = 1

# MIDI Mapping
[midi]
in_device = "X-TOUCH"
out_device = "Studio 1824c"
input = [ # XTOUCH-MINI knobs
  ["control_change", 11, 1], # XTOUCH-MINI knob controller 1
  ["control_change", 11, 2], # XTOUCH-MINI knob controller 2
  ["control_change", 11, 3], # XTOUCH-MINI knob controller 3
  ["control_change", 11, 4], # XTOUCH-MINI knob controller 4
  ["control_change", 11, 5], # XTOUCH-MINI knob controller 5 
  ["control_change", 11, 6], # XTOUCH-MINI knob controller 6
  ["control_change", 11, 7], # XTOUCH-MINI knob controller 7
  ["control_change", 11, 8], # XTOUCH-MINI knob controller 8
]
output = [ # Volca Keys: http://i.korg.com/uploads/Support/USA_volcakeys_MIDI_Chart_E.pdf
  ["note_on", 1], # note
  ["control_change", 1, 5], # Portamento
  ["control_change", 1, 40], # Voice
  ["control_change", 1, 41], # Octave
  ["control_change", 1, 42], # Detune
  ["control_change", 1, 44], # Cutoff
  ["control_change", 1, 52], # Delay Time
  ["control_change", 1, 53], # Delay Feedback
]
